<?php


namespace Marijana\Restpackage;


use Marijana\Restpackage\IRequestManager;
use Marijana\Restpackage\RequestManager;
use Closure;
use Illuminate\Support\ServiceProvider;

class BaseApiPackageServiceProvider extends ServiceProvider
{
public function register()
{
    $this->app->bind(IRequestManager::class, function($app){
        return new RequestManager($app);
    });
    $this->mergeConfigFrom(__DIR__.'/config/endpoints.php','endpionts');
    parent::register(); // TODO: Change the autogenerated stub
}
public function booted(Closure $callback)
{
    parent::booted($callback); // TODO: Change the autogenerated stub
}
}